### ISSUE TITLE
CyclicRotation

### ISSUE THREAD

**Issue by eyabc** [DKU-STUDY/Algorithm#6]

**Comment by eyabc** [comment]
[전개연산자](https://eyabc.github.io/TIL/development/React/%EC%8B%A4%EC%A0%84%EB%A6%AC%EC%95%A1%ED%8A%B8%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D/2.html#%EA%B0%9D%EC%B2%B4%EC%99%80-%EB%B0%B0%EC%97%B4%EC%9D%98-%EC%82%AC%EC%9A%A9%EC%84%B1-%EA%B0%9C%EC%84%A0) 와 concat 중 무엇을 사용해야 될까에 관한 글입니다.
https://stackoverflow.com/questions/48865710/spread-operator-vs-array-concat

**Comment by JunilHwang** [comment]
첨언을 하자면,
concat과 spread의 [성능 차이](https://www.measurethat.net/Benchmarks/Show/579/1/arrayprototypeconcat-vs-spread-operator)는 미미하고 사용용도가 다릅니다.
spread의 경우 완전히 새로운 배열을 만들 때 사용하고,
concat의 경우 기존의 배열에 이어 붙일 때 사용합니다.

```js
// a에다 이어 붙임
const a = [1, 2, 3]
a.concat([4, 5, 6])
console.log(a) // [1, 2, 3, 4, 5, 6]

// 배열을 만들어서 반환
const merge = (a, b) => [...a, ...b]
const c = merge([1, 2, 3], [4, 5, 6])
console.log(c) // [1, 2, 3, 4, 5, 6]
```

spread의 경우 원본 배열을 변경하지 않아야 할 때 사용하면 좋습니다.
