### ISSUE TITLE
스터디 참여 문의드립니다

### ISSUE THREAD

**Issue by kth496** [DKU-STUDY/Algorithm#609]
안녕하세요. 단국대학교 소프트웨어학과 김태홍이라고 합니다.

우연히 단국대 개발자 스터디를 알게 되었어요.

좋은 취지로 잘 운영되고있는 모임이라고 생각해서 합류하고 싶습니다.

마지막 모집이 7월인 것으로 확인되는데, 다음 지원 기간은 언제로 예정되어있는지 궁금합니다!

**Comment by JunilHwang** [comment]
@kth496 안녕하세요 태홍님!
https://forms.gle/X1mpLop5GP5UF1sJ8
이곳을 통해 지원해주세요~

**Comment by kth496** [comment]
@JunilHwang 
빠른 답변 감사합니다!
