### ISSUE TITLE
1차 면담

### ISSUE THREAD

**Issue by eyabc** [DKU-STUDY/Algorithm#72]
1차면담을 진행하지 못한점 죄송합니다 ㅠ 

대신 전체 면담을 진행했으면 합니다~!!  
전체 면담 내용은, 스터디 운영 방안과
질문, 건의사항, 스터디 진행 후기 각자 하고싶은 이야기 
입니다. 

방학 추가 스터디
* 준일 TDD
* 7월 이달의책
* 블로그 만들어보기
* 프론트엔드 면접 스터디
* 은영이 진행하는 아무 프로젝트 참여
* VanilaScript 미니 프로젝트 

이후 필요하다면 2:1 면담을 할 수 있습니다. 어떤 어려움이 있어 스터디 활동이 저조하다면 그 문제 해결에 도움이 되었으면 해서 진행합니다.

면담전 아래 내용을 작성해서 "박은영" 저에게 카카오톡 갠톡을 보내주시구요~

1. 스터디 개설 후 활동에 대한 평가  
    * 활동 빈도에 따라, 활동 빈도에 대한 이유가 무엇입니까? 

1. 자신이 푼 알고리즘 난이도에 대한 평가
    * 어렵다 / 적절하다 / 쉽다

1. 코드 리뷰 에 대한 평가

1. 목표로 하는 회사

1. 갖추고 싶은 기술스택

1. 스터디에 바라는점 및 만족도

1. 진로에 대한 고민 상담 

1. 알고리즘 외에 하고 싶은 스터디

1. 현재 하고있는 공부

1. 지금까지 한 공부 

--- 
본 면담에서는 스터디 운영 방안에 대한 논의를 할 것입니다.
현재는 준일님께서 수고롭게 혼자 리뷰를 해주시고 있습니다. 

그래서 제가 제안드리는 방법으로는요

문제를 제일 처음 푼 분은 준일님이 리뷰를 해주시고요
이후에 2빠 부터는
1. 나의 방식대로 문제를 푼다.
2. 이전 사람들이 푼 문제를 보고, 자신의 코드를 개선시킨다.
  -> 이전사람의 PR를 참고해도 좋고, 이해가 안된다면 PR의 댓글에 질문도 올려주세요/ 
3.  자신의 커밋을  PR 한다. 이때, assign 에 이미 문제를 푼 사람을 배정한다. 
  -> 문제푸는 방식은 언어에 상관없이 아이디어를 배울수 있음
  -> 문법에 대한 리뷰는 같은 언어를 사용하는 사람에게 리뷰 받을 수 있습니다.
4. 이미 푼사람이 평가를 해주면 (개선, 칭찬, 등등) 코드 개선 후 자신이 직접 Merge 한다.

**Comment by JeongShin** [comment]
5월 14일 목 제외하고 평일, 주말 다 가능합니다 !!

**Comment by quavious** [comment]
수, 목요일 오후 제외하고 전부 가능합니다.

**Comment by sAp00n** [comment]
이번주, 다음주 주말에 가능할꺼 같아요!

**Comment by eyabc** [comment]
Junil Hwang근데 사실 언어는 크게 상관없을 것 같아요
오후 7:08Junil Hwang어차피 엄청 고급 문법을 사용하는게 아니기때문에
오후 7:08K HW메일이 알람이 안와서 assign하고 메일을 못볼수도있으니  추가적으로 카톡으로 언급도 해야할거같아여
오후 7:08Junil Hwang제가 추천하는건
오후 7:08Junil Hwang언어 상관없이 그냥 한번씩 확인해보는건데
오후 7:08K HW네
오후 7:08신정웅넵
오후 7:08Junil Hwang일단 언어 상관없이 다른사람이 작성한걸
오후 7:08Junil Hwang한번쯤은 확인해주세요
오후 7:08Junil Hwang그리고 사실 잘 작성된 코드라면
오후 7:08Junil Hwang저희 모두 엄청 초보자 수준은 아니기때문에
오후 7:08Junil Hwang얼핏 봐도 이해할 수 있을 정도로 깔끔하게 작성하는 연습이 필요합니다
오후 7:08Junil Hwang이 코드가 그냥 개발자라면
오후 7:08Junil Hwang누구라도 이해할수 있겠구나 싶은 수준이 될때까지 리팩토링을 해보시는게 좋아요
오후 7:08Junil Hwang한번 풀이했다고 끝나는게 아니라 정말 정말
오후 7:09Junil Hwang최대한 이해하기 쉽게 만들어보는거죠
오후 7:09Junil Hwang그래서 코드리뷰를 진행하고 있는거고
오후 7:09Junil Hwang무엇보다 다른 사람이 어떻게 생각하고
오후 7:09Junil Hwang어떻게 풀이했는지 확인해보는게 필요합니다
오후 7:09Junil Hwang제가 항상 강조하는 부분인데
오후 7:09Junil Hwang개발은 혼자 하는 게 아니라
오후 7:09Junil Hwang같이 하는 것이기 때문에
오후 7:09Junil Hwang코드 뿐만 아니라 생각이나 의도 또한 공유할 수 있어야 해요
오후 7:10Junil Hwang그래서 어떻게 풀이했는지 정도는 확인해보시면 좋을 것 같아요
오후 7:10Junil Hwang가능하다면 코드리뷰까지 해주시고 그걸 추천드립니다
오후 7:10신정웅코멘트 달기에 좀 쉬운 문제나 여러 풀이가 없는 문제는 그냥 넘어가도 되나요? 
오후 7:10나이모티콘 하나정도 달아주세요 ~
오후 7:10신정웅아 넵 !! 
오후 7:11Junil Hwangㅋㅋ 그냥 좋아요 정도?는상관없을것같아요
오후 7:11Junil Hwang일단 코드리뷰는
오후 7:11Junil Hwang다른 사람을 위한것도 있지만
오후 7:11Junil Hwang자신을 위한거라고 생각해주세요
오후 7:11Junil Hwang사실 리뷰 하는 입장에서
오후 7:11Junil Hwang공부를 안하면 리뷰를 해줄 수 없거든요
오후 7:11Junil Hwang혹시 더 궁금한점 있으신가요?
오후 7:11K HW코드는 계속해서 codility의 문제로 진행되나요?
오후 7:11K HW네
오후 7:11박유림설명 감사합니다!! 그럼 제일 먼저 푼 경우 준일님이 리뷰 해주시고 , 이후에는 푼 사람들을 보고 assign을 최대한 한다음에 풀이도 할때마다 주기적으로 다른 분 풀이도 보면 되는거죠?
오후 7:12Junil Hwang음 굳이 제가 먼저 할 필요는 없을 것 같아요 ㅋㅋ

**Comment by eyabc** [comment]
1. TDD, https://edu.nextstep.camp/s/KDgLkV1d

java뿐만아니라 python.. 가능한데
python 까지는 커버 부담

객체지향의 개념이 필요
문제 코스가 존재함: 
중요한것은 , 코드리뷰를 하며 풀이하는것임.
테스트코드 작성.. ~ , 리뷰 후 피드백하는 과정 (깃허브 링크) 
객체 지향을 이해하는것이 중요. 학교에서는 활용, 쓰는이유, 중요한 개념 접근이 어려움.

시간 투자가 필요함 

질문: 
1. 자바를 어느정도 할줄알아야 하나요?  문법만 알고있어도 된다. 자세하게 알필요는 없다. 아예모르는것은 부담스럽지만 잘 몰라도 된다. 
2. 기간: 7월초 - 8월 말 
3. 몇시에 진행? 꾸준히 시간있을때하면 코드리뷰를 해준다.
4. 긍정적인 영향: 리뷰어 도우미가 있어서, 자바 혹은 타입스크립트로 진행 가능성 있음

**Comment by eyabc** [comment]
7. 7월 이달의책 : http://www.yes24.com/Product/Goods/71129079
C 컴공의 거의 모든것이 담겨있다. 재밌다

질문
1. 어떤내용을 배울 수 있나요? 베스트셀러
불: 시피유 작동방식, 기계어 작동 방식, 기계어를 작동시키는 아키텍쳐, ... 어셈블러의 필요성, 사용방법, 가상머신 만들어보기.. 등등
어려워 보이지만 쉽게 쓰여져 있다. 

고수준언어 <- 밑바닥부터 시작하는 컴퓨터 
흐름을 볼수 있는 기회

**Comment by eyabc** [comment]
3. 블로그 만들어보기
정적사이트 생성기
깃허브 -> 뷰프레스, jekyll, hexo, ....

**Comment by eyabc** [comment]
4. 프론트엔드 면접 스터디
https://gitlab.com/siots-study/topics/-/wikis/home

**Comment by eyabc** [comment]
5. 은영이 진행하는 아무 프로젝트 참여,

**Comment by eyabc** [comment]
6. VanilaScript  미니 프로젝트.  
https://academy.nomadcoders.co/p/https://github.com/eyabc/CatSearch_Clone_Vanilla
-basics-for-absolute-beginners-kr

**Comment by eyabc** [comment]
참가하고 싶은 스터디를 댓글로 작성해주세요!! 6월 30일까지!!!!

**Comment by eyabc** [comment]
슬랙이나 디스코드 활용

**Comment by khw970421** [comment]
참여할 스터디

7월 이달의책
프론트엔드 면접 스터디
VanilaScript 미니 프로젝트

(7~8월 근로장학생으로 학교에서 매주 2~3일 8시간씩 해야할거같아서 많은 스터디하기에는 어려움이 있을거같아서
근로쪽에서도 방학때 코딩쪽 관련 시킬거 같은느낌이....)

**Comment by quavious** [comment]
참여해보고 싶은 스터디입니다.
1. TDD - 하고 싶긴 한데 제가 자바는 문외한이라서 코틀린으로 해도 될지 모르겠어요. 코틀린이 된다면 문법만이라도 빠르게 배울 계획입니다.
2. 아무 프로젝트 참여 - 저 또한 계획 중인 프로젝트가 두 개 정도 있습니다. 웹 하나 모바일 하나
3. 바닐라 자바스크립트 프로젝트 - 노마드코더에 있는 바닐라 JS 강의를 다 수강하였지만, 자바스크립트에 대한 이해도를 더 높이기 위해서 참가하고 싶습니다. 리액트 익스프레스까지 배웠지만 막상 객체 지향 문법도 짤 줄 모르고, this나 바인딩에 관한 개념도 잘 숙지가 되어있지 않네요 : (
4. 이달의 책 - 3학년 1학기에 운영체제를 수강했습니다. 강의가 너무 어려워서 과제도 제대로 끝내지 못했지만 시스템의 동작을 조금이나마 배울 수 있는 계기가 되었습니다. 2학년 1학기에 컴퓨터구조론을 수강했는데 컴퓨터구조론이 너무 어려워서 공부를 하나도 하지 않았습니다. 때문에 다른 과목에서도 컴퓨터구조론과 밀접한 용어가 나오면 계속 찾아보면서 어림짐작하여 공부했습니다. 컴퓨터구조론을 다시 공부하고 싶고, 시스템에 대한 이해도가 높아져야 더 좋은 코드를 작성할 수 있을 것 같습니다.
5. 면접 스터디 - 백엔드를 지망하고 있지만 면접에 대한 지식 또한 따로 배워두어야 할 것 같습니다. 깃랩에 올라와 있는 자바스크립트 심화 내용을 제대로 공부하고 싶습니다.
감사합니다.

**Comment by JeongShin** [comment]
참여할 스터디 입니다. 
1. TDD - 자바, 타입스크립트 어느 언어를 하든 둘다 공부할 의향이 있기 때문에 잘 모르지만 열심히 공부하겠습니다 !

2. 아무 프로젝트 참여, 바닐라 자바스크립트 프로젝트 - 둘 다 희망 합니다. 아직 프로젝트 참여 경험이 없기 때문에 최대한 열심히 뭐라도 해보겠습니다 ㅠ ㅠ 
3. 이 달의 책 - 책 구매하였고 이번달도 참여 희망 합니다.
4. 블로그 만들어보기  - 현재 진행 중 입니다. 

감사합니다 !!

**Comment by pul8219** [comment]
참여하고 싶은 스터디입니다.

- 프론트엔드 면접 스터디
- 아무 프로젝트
- VanilaScript 미니 프로젝트

이번 방학에 자바스크립트 열심히 공부해보고 싶습니다! 프로젝트도  참여하여 서비스 배포까지 꼭 함께 해보고 싶습니다. 개인적인 목표는 위기모면식으로만 공부하지 말고 깊게 고민하는 공부를 체화하는 것입니다. (다른 길로 샐 때 옆에서 아낌없는 지적 주시면 감사하겠습니다.) 여러가지 기회를 만들어주셔서 정말 감사합니다.

**Comment by eyabc** [comment]
저야말로 여러분들 덕분에 좋은 기회를 얻게되었습니다:D

**Comment by sjjyy** [comment]
참여 희망하는 스터디입니다.

1. 아무 프로젝트 참여
2. VanilaScript 미니 프로젝트 - 이것도 해보고 싶은데 제가 자바스크립트를 전혀 해본적이 없어서 JS를 아예 모르면 불가능할까요? 불가하다면 1만 참여하겠습니다 ㅠㅠ!
